# Generated by Django 3.2 on 2021-05-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40, null=True, verbose_name='item_Name * ')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity')),
                ('item_type', models.CharField(max_length=40, null=True, verbose_name='item_type * ')),
                ('mode', models.CharField(max_length=40, null=True, verbose_name='mode_of_transport * ')),
                ('transport_number', models.IntegerField(null=True, verbose_name='transport Number * ')),
                ('present_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Present_Address')),
                ('Delivery_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery_Address')),
            ],
        ),
    ]
